In [1]:
import torch

x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.2687, 0.4396],
        [0.5110, 0.7001]])
tensor([[0.8798, 0.0517],
        [0.4644, 0.0605]])


In [2]:
print(x+y)
print(torch.add(x,y))

tensor([[1.1485, 0.4913],
        [0.9754, 0.7606]])
tensor([[1.1485, 0.4913],
        [0.9754, 0.7606]])


In [3]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.2687, 0.4396],
        [0.5110, 0.7001]])
tensor([[0.8798, 0.0517],
        [0.4644, 0.0605]])
tensor([[1.1485, 0.4913],
        [0.9754, 0.7606]])
