In [1]:
import torch

x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.7436, 0.8212],
        [0.3608, 0.4835]])
tensor([[0.8880, 0.2228],
        [0.4558, 0.2231]])


In [2]:
print(x)
print(y)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))


tensor([[0.7436, 0.8212],
        [0.3608, 0.4835]])
tensor([[0.8880, 0.2228],
        [0.4558, 0.2231]])
tensor([[-0.1444,  0.5984],
        [-0.0950,  0.2604]])
tensor([[-0.1444,  0.5984],
        [-0.0950,  0.2604]])
tensor([[-0.1444,  0.5984],
        [-0.0950,  0.2604]])
