In [1]:
import torch

x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.2449, 0.3035],
        [0.0107, 0.1062]])
tensor([[0.7913, 0.9732],
        [0.4276, 0.9534]])


In [3]:
print(x)
print(y)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))


tensor([[0.2449, 0.3035],
        [0.0107, 0.1062]])
tensor([[0.7913, 0.9732],
        [0.4276, 0.9534]])
tensor([[0.1938, 0.2953],
        [0.0046, 0.1013]])
tensor([[0.1938, 0.2953],
        [0.0046, 0.1013]])
tensor([[0.1938, 0.2953],
        [0.0046, 0.1013]])
