In [2]:
import torch

x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.3338, 0.8659],
        [0.1821, 0.4261]])
tensor([[0.2618, 0.9783],
        [0.4670, 0.8028]])


In [3]:
print(x)
print(y)
print(x/y)
print(torch.div (x,y))
print(x.div (y))


tensor([[0.3338, 0.8659],
        [0.1821, 0.4261]])
tensor([[0.2618, 0.9783],
        [0.4670, 0.8028]])
tensor([[1.2754, 0.8851],
        [0.3899, 0.5308]])
tensor([[1.2754, 0.8851],
        [0.3899, 0.5308]])
tensor([[1.2754, 0.8851],
        [0.3899, 0.5308]])
