In [1]:
import torch

x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.9824, 0.4105],
        [0.7154, 0.6873]])
tensor([[0.1352, 0.0361],
        [0.3277, 0.8578]])


In [2]:
print(x)
print(y)
print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)
print(torch.svd(z))

tensor([[0.9824, 0.4105],
        [0.7154, 0.6873]])
tensor([[0.1352, 0.0361],
        [0.3277, 0.8578]])
tensor([[0.2673, 0.3876],
        [0.3219, 0.6153]])
tensor([[0.2673, 0.3876],
        [0.3219, 0.6153]])
torch.return_types.svd(
U=tensor([[-0.5601, -0.8284],
        [-0.8284,  0.5601]]),
S=tensor([0.8377, 0.0474]),
V=tensor([[-0.4971, -0.8677],
        [-0.8677,  0.4971]]))
